### ISSUE TITLE
search error with 401

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [imki123/catbook#20]
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/4844714/215389104-51d3c3c2-2818-4cd6-9433-0a94c21e7529.png">
on search

**Comment by imki123** [comment]
@LoveMeWithoutAll Thank you for telling me. I'll check it.

**Comment by imki123** [comment]
@LoveMeWithoutAll Back-end server has been expired. I'll change server. It will be resolved soon.

**Comment by imki123** [comment]
@LoveMeWithoutAll `Backend server is changed`. Resolved. Thank you.

<img width="1113" alt="스크린샷 2023-01-30 오후 2 12 55" src="https://user-images.githubusercontent.com/43270441/215392791-a97a570e-9b28-4d0a-a200-b6b229bfe10c.png">

**Comment by LoveMeWithoutAll** [comment]
thank you
